version: "2"

linters:
  enable:
    - staticcheck    # 潜在バグ・非推奨API・パフォーマンス系などのチェック
    - errcheck       # エラー戻り値の無視を検出。Goで重要なエラーハンドリングを強化
    - ineffassign    # 無意味な代入（使われていない変数代入）を検出
    - unparam        # 未使用の関数パラメータを検出。リファクタ候補の特定に有効
    - gosec          # セキュリティリスクのあるコードパターンを検出（例：ハードコード鍵）
    - gocritic       # バグの可能性・改善余地のある構造を網羅的にチェック
    - misspell       # 誤字の検出（ドキュメントやコメント品質の向上に寄与）
    - errorlint      # `%w` の使用適正など、エラーラップの問題を検出
    # - revive         # 命名規則やコメントスタイルなど、スタイル規約をチェック
    - cyclop         # 関数の複雑さ（条件分岐のネスト）を検出
    - unused         # 使われていない変数や関数など、不要コードを検出して整理

formatters:
  enable:
    - goimports      # import 文の並び替え＋未使用/不足importの整理を自動化
    - gofumpt        # `gofmt` に準拠しつつ、意見のある整形ルールを追加した最新版

  settings:
    gofumpt:
      module-path: tech-stock
      extra-rules: true
