// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: article_info.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetArticleInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleInfoRequest) Reset() {
	*x = GetArticleInfoRequest{}
	mi := &file_article_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleInfoRequest) ProtoMessage() {}

func (x *GetArticleInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleInfoRequest.ProtoReflect.Descriptor instead.
func (*GetArticleInfoRequest) Descriptor() ([]byte, []int) {
	return file_article_info_proto_rawDescGZIP(), []int{0}
}

func (x *GetArticleInfoRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetArticleInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleInfoResponse) Reset() {
	*x = GetArticleInfoResponse{}
	mi := &file_article_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleInfoResponse) ProtoMessage() {}

func (x *GetArticleInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_article_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleInfoResponse.ProtoReflect.Descriptor instead.
func (*GetArticleInfoResponse) Descriptor() ([]byte, []int) {
	return file_article_info_proto_rawDescGZIP(), []int{1}
}

func (x *GetArticleInfoResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetArticleInfoResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetArticleInfoResponse) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

var File_article_info_proto protoreflect.FileDescriptor

const file_article_info_proto_rawDesc = "" +
	"\n" +
	"\x12article_info.proto\x12\farticle_info\")\n" +
	"\x15GetArticleInfoRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"m\n" +
	"\x16GetArticleInfoResponse\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1b\n" +
	"\timage_url\x18\x03 \x01(\tR\bimageUrl2s\n" +
	"\x12ArticleInfoService\x12]\n" +
	"\x0eGetArticleInfo\x12#.article_info.GetArticleInfoRequest\x1a$.article_info.GetArticleInfoResponse\"\x00B\x12Z\x10tech-stock/pb;pbb\x06proto3"

var (
	file_article_info_proto_rawDescOnce sync.Once
	file_article_info_proto_rawDescData []byte
)

func file_article_info_proto_rawDescGZIP() []byte {
	file_article_info_proto_rawDescOnce.Do(func() {
		file_article_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_article_info_proto_rawDesc), len(file_article_info_proto_rawDesc)))
	})
	return file_article_info_proto_rawDescData
}

var file_article_info_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_article_info_proto_goTypes = []any{
	(*GetArticleInfoRequest)(nil),  // 0: article_info.GetArticleInfoRequest
	(*GetArticleInfoResponse)(nil), // 1: article_info.GetArticleInfoResponse
}
var file_article_info_proto_depIdxs = []int32{
	0, // 0: article_info.ArticleInfoService.GetArticleInfo:input_type -> article_info.GetArticleInfoRequest
	1, // 1: article_info.ArticleInfoService.GetArticleInfo:output_type -> article_info.GetArticleInfoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_article_info_proto_init() }
func file_article_info_proto_init() {
	if File_article_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_article_info_proto_rawDesc), len(file_article_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_article_info_proto_goTypes,
		DependencyIndexes: file_article_info_proto_depIdxs,
		MessageInfos:      file_article_info_proto_msgTypes,
	}.Build()
	File_article_info_proto = out.File
	file_article_info_proto_goTypes = nil
	file_article_info_proto_depIdxs = nil
}
