// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: image.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SaveImageOfUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveImageOfUrlRequest) Reset() {
	*x = SaveImageOfUrlRequest{}
	mi := &file_image_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveImageOfUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveImageOfUrlRequest) ProtoMessage() {}

func (x *SaveImageOfUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_image_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveImageOfUrlRequest.ProtoReflect.Descriptor instead.
func (*SaveImageOfUrlRequest) Descriptor() ([]byte, []int) {
	return file_image_proto_rawDescGZIP(), []int{0}
}

func (x *SaveImageOfUrlRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type SaveImageOfUrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectKey     string                 `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveImageOfUrlResponse) Reset() {
	*x = SaveImageOfUrlResponse{}
	mi := &file_image_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveImageOfUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveImageOfUrlResponse) ProtoMessage() {}

func (x *SaveImageOfUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_image_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveImageOfUrlResponse.ProtoReflect.Descriptor instead.
func (*SaveImageOfUrlResponse) Descriptor() ([]byte, []int) {
	return file_image_proto_rawDescGZIP(), []int{1}
}

func (x *SaveImageOfUrlResponse) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

type GetImageUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectKey     string                 `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImageUrlRequest) Reset() {
	*x = GetImageUrlRequest{}
	mi := &file_image_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImageUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageUrlRequest) ProtoMessage() {}

func (x *GetImageUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_image_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageUrlRequest.ProtoReflect.Descriptor instead.
func (*GetImageUrlRequest) Descriptor() ([]byte, []int) {
	return file_image_proto_rawDescGZIP(), []int{2}
}

func (x *GetImageUrlRequest) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

type GetImageUrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PresignedUrl  string                 `protobuf:"bytes,1,opt,name=presigned_url,json=presignedUrl,proto3" json:"presigned_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImageUrlResponse) Reset() {
	*x = GetImageUrlResponse{}
	mi := &file_image_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImageUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageUrlResponse) ProtoMessage() {}

func (x *GetImageUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_image_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageUrlResponse.ProtoReflect.Descriptor instead.
func (*GetImageUrlResponse) Descriptor() ([]byte, []int) {
	return file_image_proto_rawDescGZIP(), []int{3}
}

func (x *GetImageUrlResponse) GetPresignedUrl() string {
	if x != nil {
		return x.PresignedUrl
	}
	return ""
}

var File_image_proto protoreflect.FileDescriptor

const file_image_proto_rawDesc = "" +
	"\n" +
	"\vimage.proto\x12\x05image\")\n" +
	"\x15SaveImageOfUrlRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"7\n" +
	"\x16SaveImageOfUrlResponse\x12\x1d\n" +
	"\n" +
	"object_key\x18\x01 \x01(\tR\tobjectKey\"3\n" +
	"\x12GetImageUrlRequest\x12\x1d\n" +
	"\n" +
	"object_key\x18\x01 \x01(\tR\tobjectKey\":\n" +
	"\x13GetImageUrlResponse\x12#\n" +
	"\rpresigned_url\x18\x01 \x01(\tR\fpresignedUrl2\xa3\x01\n" +
	"\fImageService\x12M\n" +
	"\x0eSaveImageOfUrl\x12\x1c.image.SaveImageOfUrlRequest\x1a\x1d.image.SaveImageOfUrlResponse\x12D\n" +
	"\vGetImageUrl\x12\x19.image.GetImageUrlRequest\x1a\x1a.image.GetImageUrlResponseB\x12Z\x10tech-stock/pb;pbb\x06proto3"

var (
	file_image_proto_rawDescOnce sync.Once
	file_image_proto_rawDescData []byte
)

func file_image_proto_rawDescGZIP() []byte {
	file_image_proto_rawDescOnce.Do(func() {
		file_image_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_image_proto_rawDesc), len(file_image_proto_rawDesc)))
	})
	return file_image_proto_rawDescData
}

var file_image_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_image_proto_goTypes = []any{
	(*SaveImageOfUrlRequest)(nil),  // 0: image.SaveImageOfUrlRequest
	(*SaveImageOfUrlResponse)(nil), // 1: image.SaveImageOfUrlResponse
	(*GetImageUrlRequest)(nil),     // 2: image.GetImageUrlRequest
	(*GetImageUrlResponse)(nil),    // 3: image.GetImageUrlResponse
}
var file_image_proto_depIdxs = []int32{
	0, // 0: image.ImageService.SaveImageOfUrl:input_type -> image.SaveImageOfUrlRequest
	2, // 1: image.ImageService.GetImageUrl:input_type -> image.GetImageUrlRequest
	1, // 2: image.ImageService.SaveImageOfUrl:output_type -> image.SaveImageOfUrlResponse
	3, // 3: image.ImageService.GetImageUrl:output_type -> image.GetImageUrlResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_image_proto_init() }
func file_image_proto_init() {
	if File_image_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_image_proto_rawDesc), len(file_image_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_image_proto_goTypes,
		DependencyIndexes: file_image_proto_depIdxs,
		MessageInfos:      file_image_proto_msgTypes,
	}.Build()
	File_image_proto = out.File
	file_image_proto_goTypes = nil
	file_image_proto_depIdxs = nil
}
